### ISSUE TITLE
CLI error (possible incompatibility with Rails 7?)

### ISSUE THREAD

**Issue by delongtj** [kawamataryo/schema2type#11]
Ruby Version: 3.1.2
Rails Version: 7.0.2.4
Gem version: 0.4.0

When following the instructions in README and running this command:
```
bundle exec schema2type -o schema.d.ts
```

I am receiving the following error:
```
bundler: failed to load command: schema2type (/Users/tydelong/.rbenv/versions/3.1.2/bin/schema2type)
(eval):13:in `get_binding': undefined method `[]' for Schema2type::CovertService::ActiveRecord::Schema:Module (NoMethodError)
        from /Users/tydelong/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/schema2type-0.4.0/lib/schema2type/cli.rb:6:in `eval'
        from /Users/tydelong/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/schema2type-0.4.0/lib/schema2type/cli.rb:6:in `execute'
        from /Users/tydelong/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/schema2type-0.4.0/exe/schema2type:8:in `<top (required)>'
        from /Users/tydelong/.rbenv/versions/3.1.2/bin/schema2type:25:in `load'
        from /Users/tydelong/.rbenv/versions/3.1.2/bin/schema2type:25:in `<top (required)>'
 ...
 ```

 I traced it as far as seeing that it is coming from the `binding` call in `Schema2type::CovertService`, but it's not clear to me where the method call to `[]` is coming from.

One guess I have is [this method](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/schema.rb#L69) which was added sometime between Rails 6 and 7.  That same class was also changed to `extend ActiveSupport::Concern` with the major version change.

I've never dealt with `binding` like this before, so forgive me if this hypothesis is off-track. I am happy to provide any additional information or context necessary.

Thanks!

**Comment by kawamataryo** [comment]
Thanks for the Issue.
I'm not able to do much maintenance on this library right now.

Please give me a few days.

**Comment by delongtj** [comment]
Thanks for the response, and no worries.

[This gem](https://github.com/aviemet/ts_schema) ended up working for my team's purposes for now.

Let me know if I can help debug or test anything further with this issue.
