### ISSUE TITLE
NoMethodError: undefined method `map' for nil:NilClass

### ISSUE THREAD

**Issue by snaptopixel** [kawamataryo/schema2type#5]
Greetings and thank you for writing this lib!

Trying it out on a project and it's not working:

```
$ bundle exec schema2type -o frontend/src/schema.d.ts
bundler: failed to load command: schema2type (/Users/casey/.asdf/installs/ruby/2.7.0/bin/schema2type)
NoMethodError: undefined method `map' for nil:NilClass
  /Users/casey/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/schema2type-0.3.0/lib/schema2type/covert_service.rb:34:in `define'
  /Users/casey/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/schema2type-0.3.0/lib/schema2type/covert_service.rb:21:in `get_binding'
  /Users/casey/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/schema2type-0.3.0/lib/schema2type/cli.rb:6:in `eval'
  /Users/casey/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/schema2type-0.3.0/lib/schema2type/cli.rb:6:in `execute'
  /Users/casey/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/schema2type-0.3.0/exe/schema2type:8:in `<top (required)>'
  /Users/casey/.asdf/installs/ruby/2.7.0/bin/schema2type:23:in `load'
  /Users/casey/.asdf/installs/ruby/2.7.0/bin/schema2type:23:in `<top (required)>'
```

**Comment by snaptopixel** [comment]
When I comment this out it works...
```rb
  # add_foreign_key "active_storage_attachments", "active_storage_blobs", column: "blob_id"
```

**Comment by kawamataryo** [comment]
@snaptopixel 

Thanks for your issue. This is solved  at https://github.com/kawamataryo/schema2type/pull/6
